name: Version Increment

on:
  push:
    branches: ['main']

jobs:
  patch-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_ACCESS }}
      - name: Set github user name
        if: ${{ github.event_name == 'push' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          npm version patch -m "[INCREASE APP VERSION] %s"
          git push
