name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git config user.name github-actions[bot]
      - run: git config user.email github-actions[bot]@users.noreply.github.com
      - run: npm version patch -m "[INCREASE APP VERSION] %s"
      - run: git push
