name: Version Increment

on:
  push:
    branches: ['main']

jobs:
  patch-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Commit patch version
        if: ${{ github.event_name == 'push' && github.actor == 'github-actions[bot]@users.noreply.github.com' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          npm version patch -m "[INCREASE APP VERSION] %s"
      - name: Push changes
        if: ${{ github.event_name == 'push' && github.actor == 'github-actions[bot]@users.noreply.github.com' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADMIN_ACCESS }}
          branch: ${{ github.ref }}
