name: Version Increment

on:
  push:
    branches: ['main']

jobs:
  patch-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Set github user name
        if: ${{ github.event_name == 'push' }}
        run: git config user.name github-actions[bot]
      - name: Set github user email
        if: ${{ github.event_name == 'push' }}
        run: git config user.email github-actions[bot]@users.noreply.github.com
      - name: Patch app version
        if: ${{ github.event_name == 'push' }}
        run: npm version patch -m "[INCREASE APP VERSION] %s"
      - name: Git push
        if: ${{ github.event_name == 'push' }}
        run: git push
